URL_APP_LIST : "https://api.steampowered.com/ISteamApps/GetAppList/v2"
URL_CONCURRENT_USER : "https://api.steampowered.com/ISteamUserStats/GetNumberOfCurrentPlayers/v1/"

DB_URL : "mongodb+srv://user_nobel:rocketboy7!@nobelcluster2-ufvc0.mongodb.net/test?retryWrites=true"